name: Upload to S3

on:
  push:
    branches:
      - master 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_S3_BUCKET: ${{ secrets.AWS_S3BUCKET_NAME }}
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
          cd ./code/lib
          zip -r corelib.zip ./corelib 
          aws s3 cp corelib.zip s3://$AWS_S3_BUCKET/lib/
          cd ../..
          aws s3 sync ./code/ s3://$AWS_S3_BUCKET/ --exclude ./code/lib/*.py