name: Upload to S3

on:
  push:
    branches:
      - master 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_S3_BUCKET: ${{ secrets.AWS_S3BUCKET_NAME }}
          TEST: "yes"
          PROD: "no"
        run: |
          chmod +x ./code/deploy.sh
          ./code/deploy.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_DEFAULT_REGION $AWS_S3_BUCKET $TEST $PROD